server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupondb?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root

  application:
    name: COUPON-SERVICE
    